[project]
name = "noisefinder"
version = "0.2.0"
description = "Precise Bayesian spectral estimation and noise projection for time series."
authors = [
    {name = "Lorenzo Sala"}
]
license = {text = "BSD-3-Clause"}
readme = "README.md"
requires-python = ">=3.10"
keywords = [
    "spectral estimation",
    "power spectral density",
    "noise projection",
    "bayesian inference",
    "time series",
]
dependencies = [
    "numpy (>=2.0.2)",
    "scipy (>=1.13.1)",
    "mpmath (>=1.3.0)"
]

[project.urls]
Homepage = "https://lorsala.github.io/noisefinder/"
Documentation = "https://lorsala.github.io/noisefinder/"
Repository = "https://github.com/lorsala/noisefinder"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
exclude = [
    ".ipynb_checkpoints",
    "noisefinder/ipynb_checkpoints",
]

[tool.poetry.group.test.dependencies]
pytest = "^8.0"

[tool.poetry.group.docs.dependencies]
sphinx = "^8.0"
myst-parser = "^4.0"
myst-nb = "^1.4"
sphinx-mdinclude = "^0.6.2"
sphinx-rtd-theme = "^3.1.0"
linkify-it-py = "^2.0"
