[project]
name = "noisefinder"
version = "1.0"
description = ""
authors = [
    {name = "Lorenzo Sala"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy (>=2.0.2,<3.0.0)",
    "scipy (>=1.13.1,<2.0.0)",
    "mpmath (>=1.3.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

exclude = [
    ".ipynb_checkpoints",
    "noisefinder/ipynb_checkpoints",
]