[project]
name = "noisefinder"
version = "0.1.0"
description = ""
authors = [
    {name = "Lorenzo Sala"}
]
license = {text = "BSD-3"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy (>=2.0.2)",
    "scipy (>=1.13.1)",
    "mpmath (>=1.3.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

exclude = [
    ".ipynb_checkpoints",
    "noisefinder/ipynb_checkpoints",
]

[tool.poetry.group.test.dependencies]
pytest = "^8.0"

[tool.poetry.group.docs.dependencies]
sphinx = "^8.0"
myst-parser = "^4.0"
sphinx-mdinclude = "^0.6.2"
sphinx-rtd-theme = "^3.1.0"
